name: GS Engine Benchmark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-benchmarks:
    runs-on: windows-latest
    
    strategy:
      fail-fast: false # If one suite fails, let the others finish running
      matrix:
        suite: [Storage, Memory, Processing, Hardware]

    name: Suite - ${{ matrix.suite }}

    steps:
      - name: Checkout Core Repo
        uses: actions/checkout@v4
        with:
          path: core

      - name: Checkout Benchmark Repo
        uses: actions/checkout@v4
        with:
          repository: GS-SystemAnalyzer/gs-benchmark 
          path: gs-benchmarks
          token: ${{ secrets.BENCHMARK_REPO_TOKEN }}

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Execute ${{ matrix.suite }} Benchmarks
        env:
          CoreRepoPath: ${{ github.workspace }}\core
        working-directory: .\gs-benchmarks\GSAnalyzer.Benchmarks
        run: dotnet run -c Release -- --filter "*GSAnalyzer.Benchmarks.Suites.${{ matrix.suite }}.*"

      - name: Notify Discord
        continue-on-error: true
        uses: sarisia/actions-status-discord@v1
        if: always() 
        with:
          webhook: ${{secrets.CI_BUILD}}
          title: "GS Engine Benchmark: ${{ matrix.suite }}"
